### ISSUE TITLE
New installation failures: ExtUtils::MakeMaker version 7 required

### ISSUE THREAD

**Issue by oalders** [petdance/html-tagset#6]
As of today, I'm seeing this in CI:

> Error: 2024-03-11T01:10:24,1825,HTML-Tagset-3.22| ExtUtils::MakeMaker version 7 required--this is only version 6.66 at Makefile.PL line 7.

See https://github.com/libwww-perl/LWP-Protocol-https/actions/runs/8226201975/job/22492333510

**Comment by petdance** [comment]
Updated the cpanfile and dropped it to 6.46 of EU::MM.

**Comment by oalders** [comment]
@petdance do you have plans for a release with this fix or would you like someone else to do that from this point?

**Comment by petdance** [comment]
Alredy did.

https://metacpan.org/dist/HTML-Tagset/changes

https://metacpan.org/release/PETDANCE/HTML-Tagset-3.24/source/META.json

**Comment by oalders** [comment]
Wonderful. Thank you!
